portfolio_project/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('works/', views.WorksView.as_view(), name='works'),
    path('contacts/', views.ContactView.as_view(), name='contacts'),
]

portfolio_project/portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_project/main_app/models.py
from django.db import models
from tinymce.models import HTMLField


class TextInformation(models.Model):
    header = models.CharField('Header', max_length=200, null=False, blank=False)
    text = HTMLField('Text', max_length=5000, null=False, blank=False)

    def __str__(self):
        return self.header
    
    class Meta:
        verbose_name = 'Text information'
        verbose_name_plural = 'Texts information'


class Certificate(models.Model):
    school = models.CharField('School name', max_length=200, null=False, blank=False)
    course = models.CharField('Course name', max_length=200, null=False, blank=False)
    duration = models.CharField('Course duration', max_length=200, null=True, blank=True)
    date = models.DateField('Certificate date', null=True, blank=True)
    image = models.ImageField(upload_to='certificates/')

    def __str__(self):
        return f'{self.course} from {self.school}'
    
    class Meta:
        verbose_name = 'Certificate'
        verbose_name_plural = 'Certificates'


class ProjectInformation(models.Model):
    name = models.CharField('Project name', max_length=200, null=False, blank=False)
    description = HTMLField('Project description', max_length=5000, null=False, blank=False)
    date = models.DateField('Date finished', null=True, blank=True)
    link = models.URLField('Github link', max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'


class Screenshot(models.Model):
    project = models.ForeignKey(ProjectInformation, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='screenshots/')

    def __str__(self):
        return f'Screenshot of {self.project.name}'
    
    class Meta:
        verbose_name = 'Screenshot'
        verbose_name_plural = 'Screenshots'

portfolio_project/main_app/views.py
from typing import Any
from django.shortcuts import render
from django.views import generic
from . import models


class IndexView(generic.TemplateView):
    template_name = 'portfolio/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        welcome = models.TextInformation.objects.get(id=1)
        learning = models.TextInformation.objects.get(id=2)
        context['welcome'] = welcome.text
        context['learning'] = learning.text
        context['certificates'] = models.Certificate.objects.all().order_by('date')
        return context


class WorksView(generic.TemplateView):
    template_name = 'portfolio/works.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = models.ProjectInformation.objects.all().order_by('-date')
        return context
    

class ContactView(generic.TemplateView):
    template_name = 'portfolio/contacts.html'

portfolio_project/main_app/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Daiva Reinike portfolio</title>
        <link rel="icon" href="{% static 'img/favicon.ico '%}" type="image/x-icon">
        <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/custom-bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <nav>
            <ul class="flex-menu">
                <li class="menu-float-left">
                    <img src="{% static 'img/python.png' %}" alt="Python logo">
                </li>
                <li>
                    <a href="{% url 'index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'works' %}">Works</a>
                </li>
                <li>
                    <a href="{% url "contacts" %}">Contact</a>
                </li>
            </ul>
        </nav>
        <header>
            <div class="flex-header">
                <div class="auto-write">
                    <h1>Hi, my name is Daiva</h1>
                    <h2>I am a Junior Python Developer</h2>
                </div>     
            </div>
        </header>
        <main>
            {% block content %}{% endblock content %}
        </main>
        <aside>
            <div class="sidebar-container">
                <div>
                  <h4>Your time</h4>
                  <div id="your-time"></div>
                </div>
                <div>
                    <h4>My time</h4>
                    <div id="my-time"></div>
                  </div>
                  <div>
                    <h4>Find me here</h4>
                    <ul class="link-img">
                        <li>
                            <a href="https://github.com/reinikeda" target="_blank"><img src="{% static 'img/github.png' %}" alt="Github logo"></a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/in/daiva-reinike" target="_blank"><img src="{% static 'img/linkedin.png' %}" alt="LinkedIn logo"></a>
                        </li>
                    </ul>
                </div>
            </div>        
        </aside>
        <footer>
            <div>&copy; 2023 Daiva Reinikė</div>
        </footer>
        <script src="{% static 'js/clock.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

portfolio_project/main_app/templates/portfolio/contacts.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>CONTACT ME</h1>
<hr>
<div>
    <p>Sorry, contact form is not working. Please send email directly to <a href = "mailto: reinikeda@gmail.com">reinikeda@gmail.com</a> or contact via <a href="https://github.com/reinikeda" target="_blank">GitHub</a> or <a href="https://www.linkedin.com/in/daiva-reinike" target="_blank">LinkedIn</a>.</p>
</div>
{% endblock content %}

portfolio_project/main_app/templates/portfolio/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>WELCOME TO MY PORTFOLIO!</h1>
<hr>
<div class="content-flex">
    <div class="image-center">
        <img src="{% static 'img/me.jpg' %}" alt="My photo" class="round-picture">
    </div>
    <div>
        {% if welcome %}
            {{ welcome|safe }}
        {% else %}
            <p>Error. No database found.</p>
        {% endif %}
    </div>
</div>
<hr>
<div class="content-flex">
    <div class="image-center">
        {% if certificates %}
            <div id="carousel-certificates" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for certificate in certificates %}
                        <li data-target="#carousel-certificates" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for certificate in certificates %}
                        <div class="carousel-item{% if forloop.first %} active{% endif %}">
                            <img src="{{ certificate.image.url }}" alt="{{ certificate.course }} certificate" class="carousel-image">
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carousel-certificates" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                </a>
                <a class="carousel-control-next" href="#carousel-certificates" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </a>
            </div>
        {% else %}
            <p>Error. No database found.</p>
        {% endif %}
    </div>
    <div class="tinymce-link">
        {% if learning %}
            {{ learning|safe }}
        {% else %}
            <p>Error. No database found.</p>
        {% endif %}
    </div>
</div>
<hr class="last-line">
{% endblock content %}

portfolio_project/main_app/templates/portfolio/works.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1>MY WORKS</h1>
<hr>
{% if projects %}
    {% for project in projects %}
    <div>
        <div>
            <h2>{{ project.name }}</h2>
        </div>
        <div class="content-flex">
            <div class="image-center">
                <div id="carousel-{{ project.id }}" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for screenshot in project.screenshot_set.all %}
                            <li data-target="#carousel-{{ project.id }}" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for screenshot in project.screenshot_set.all %}
                            <div class="carousel-item{% if forloop.first %} active{% endif %}">
                                <img src="{{ screenshot.image.url }}" alt="{{ project.name }} screenshot" class="carousel-image">
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carousel-{{ project.id }}" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    </a>
                    <a class="carousel-control-next" href="#carousel-{{ project.id }}" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    </a>
                </div>
            </div>        
            <div>
                <div>{{ project.description|safe }}</div>
                <div class="link-img-2"><a href="{{ project.link }}" target="_blank">Github link to project<img src="{% static 'img/github.png' %}" alt="Github logo"></a></div>
            </div>
        </div>
    </div>
    <hr class="line">
    {% endfor %}
{% else %}
    <p>Error. No database found.</p>
{% endif %}
{% endblock content %}